.github/workflows/master.yml
Sets the version correctly in the master pipeline
=> set correct prerelease version

Makefile, provider/cmd/pulumi-gen-aws-native/main.go
=> Discovery downloads JSON schemas

.github/workflows/pull_request.yml
=> Add schema tools check to PRs

.github/workflows/nightly-sdk-generation.yml
My take on #178
I haven't tested it - I suggest we merge and watch :)
=> Nightly SDK generation

CHANGELOG.md, provider/pkg/provider/provider.go
=> Add support for specifying max retries

CHANGELOG.md, provider/cmd/pulumi-resource-aws-native/schema.json, provider/pkg/schema/gen.go, sdk/dotnet/Provider.cs, sdk/go/aws/provider.go, sdk/nodejs/provider.ts, sdk/python/pulumi_aws_native/provider.py
=> Avoid potentially spilling credentials to state

README.md
- Point to native version rather than classic.
=> Fix link to setup guide

CHANGELOG.md, provider/pkg/provider/provider.go
Explain how to set the missing value (matches pulumi-aws format).
Closes #220
=> Add detail to missing region config error

.github/workflows/release.yml
Adopt recommendation from https://github.com/pulumi/ci-mgmt/issues/137#issuecomment-1054516616
=> Add tag_sdk step to release GHA spec

.github/workflows/nightly-sdk-generation.yml, .github/workflows/weekly-pulumi-update.yml
Resolves #https://github.com/pulumi/home/issues/1965
=> Use native automerge

.github/workflows/nightly-sdk-generation.yml
This step shouldn't be needed, currently no PR will be created if there are no changes.
=> Remove PR conditional

.github/workflows/nightly-sdk-generation.yml, .github/workflows/weekly-pulumi-update.yml
Validated that this will fix here: https://github.com/pulumi/pulumi-aws-native/actions/runs/2168354510
=> Fix weekly update action

provider/pkg/provider/provider_intrinsics.go
getAzs was returning empty response. This fixes it.
=> Fix getAzs function

.github/workflows/weekly-pulumi-update.yml
- restore `make init_submodules`
=> [internal] fix weekly Pulumi update

provider/pkg/provider/provider.go
Fixes #676
Sometimes cloudcontrol doesn't return a status code of 404, but returns a generic 400 which includes "ResourceNotFoundException" in the message.
There's no current simple way of testing this with program test and actually asserting on the refresh behaviour so I think I'll need to build a new testing framework to add adequete testing here. (Have tested manually)
=> Fix reading resources which have been deleted

provider/cmd/pulumi-gen-aws-native/main.go
Don't automatically remove types once they've been published.
=> Make supported resources append-only

.github/workflows/build.yml, .github/workflows/cf2pulumi-release.yml, .github/workflows/command-dispatch.yml, .github/workflows/nightly-sdk-generation.yml, .github/workflows/prerelease.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, .github/workflows/run-acceptance-tests.yml, .github/workflows/weekly-pulumi-update.yml, provider/go.mod, provider/pkg/schema/gen.go, sdk/dotnet/KinesisAnalytics/ApplicationOutputResource.cs, sdk/dotnet/KinesisAnalyticsV2/ApplicationOutputResource.cs, sdk/go/aws/kinesisanalytics/applicationOutputResource.go, sdk/go/aws/kinesisanalyticsv2/applicationOutputResource.go, sdk/nodejs/kinesisanalytics/applicationOutputResource.ts, sdk/nodejs/kinesisanalyticsv2/applicationOutputResource.ts, sdk/python/pulumi_aws_native/kinesisanalytics/application_output_resource.py, sdk/python/pulumi_aws_native/kinesisanalyticsv2/application_output_resource.py
1. Generalise naming in typeName function.
2. Call into typeName function from typeToken and moduleName functions.
3. Add extra assert when splitting moduleName token.
=> Generalise existing workaround for resource with Output suffix

sdk/go.mod
=> Bump Go version in sdk/go.mod to unblock mod tidy

examples/aws-native-naming-conventions/package-lock.json, examples/aws-native-naming-conventions/package.json
Combining multiple dependencies PRs into one.
<details>
<summary>Instructions for merging</summary>
* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.
</details>
* Bump semver from 5.7.1 to 5.7.2 in /examples/aws-native-naming-conventions (#974) @app/dependabot
* Bump @grpc/grpc-js and @pulumi/pulumi in /examples/aws-native-naming-conventions (#964) @app/dependabot
=> Combined dependencies PR

CHANGELOG.md
Resource summary from https://github.com/pulumi/pulumi-aws-native/pull/1201.
=> Prepare v0.90.0

provider/pkg/provider/provider.go
Fixes #114 
This allows us to perform previews without needing to have credentials configured.
Side note - it seems as if the not implemented validation for "skip..." are wrong too as they only trigger if the value is set to a falsy value i.e. don't skip. They don't trigger when "skip" is set to true even though the skip is not actually implemented.
Extracted from #1292
=> Implement skipping credentials validation

CHANGELOG.md, README.md
=> Prepare 0.96.0

.github/workflows/build.yml, .github/workflows/cf2pulumi-release.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml
re https://github.com/pulumi/ci-mgmt/pull/1008
=> chore: update macos runner version

provider/pkg/schema/gen.go, sdk/dotnet/Pulumi.AwsNative.csproj
Re: https://github.com/pulumi/ci-mgmt/issues/1091
=> Revert .NET changes

.github/workflows/weekly-pulumi-update.yml
Fixes https://github.com/pulumi/pulumi-aws-native/issues/1971 P1
Applying a known workaround to a GitHub CLI issue.
=> chore: fix weekly-pulumi-update
