README.md
sdk/python/README.md

Let's ensure that the README clearly indicates that the AWS Native provider is in public preview.

Add preview note to README

---

provider/pkg/cf2pulumi/renderer.go

In https://github.com/pulumi/pulumi-aws-native/issues/149, we are panicking trying to convert a valid CloudFormation template. The root cause for that is that a map doesn't ever get initialized, leading to an "assignment to entry in nil map" panic on any code paths that try to use it. Fix is simple: initialize it to an empty map.
Unfortunately, that yields a new error, `failed to render template: unsupported property 'Condition' in resource 'Leaf5'`. That is caused by the following YAML
```
Conditions:
CreateLeaf5: !Or
- !Condition 'CreateLeaf6'
- !Equals
- !Ref 'NumLeaves'
- 5
```
It appears we don't support referencing other conditions from within conditions. I'm not sure how easy that will be to fix, but I figure fixing the panic is a good thing to get in regardless.

Fix a panic in cf2pulumi codepath

---

CHANGELOG.md
provider/pkg/provider/provider.go

It is semantically wrong to statically populate the `Replaces` property of a Diff response with all the properties that require replacement for a given resource type. This PR removes this, which means we will detect _no_ replacements. I think this is a better type of error than unneeded replacements. 
We should follow-up with a proper fix with https://github.com/pulumi/pulumi-aws-native/issues/175 (or a detailed diff calculation if #175 turns out not to work).
Fix #186
Fix #204

Stop unconditional population of Replaces in Diff

---

CHANGELOG.md
provider/go.mod
provider/pkg/provider/provider.go
provider/pkg/schema/convert.go

Even in case of creation failure, check if the progress event contains a resource identifier. If so, try reading its state and treat the operation as partially succeeded.
Added a nil check in patch calculation because:
- The resource was created with properties A
- Cloud Control reported it as failed but it actually succeeded
- On the next run, Pulumi detects an update (to complete the operation) but the properties are still A
- We calculate the diff between A and A and get an empty diff (nil)
- Provider panicked in patch calculation
Fixes the orphaned resource part of #184

Record state for a resource that partially failed to create

---

CHANGELOG.md
provider/pkg/provider/provider.go

I think this fixes https://github.com/pulumi/pulumi-aws-native/issues/192
I was able to reproduce similar errors and saw that `RetryAfter` reported by the service was in the past, which made us retry immediately.
I also added some extra logging to help debug issues related to retries if they remain.

Check retry after is in the future

---

CHANGELOG.md
examples/examples_nodejs_test.go
examples/update/step1/Pulumi.yaml
examples/update/step1/index.ts
examples/update/step1/package.json
examples/update/step1/tsconfig.json
examples/update/step2/Pulumi.yaml
examples/update/step2/index.ts
examples/update/step2/package.json
examples/update/step2/tsconfig.json
provider/pkg/schema/convert.go
provider/pkg/schema/convert_test.go

Fix #230
Not sure why we previously decided to serialize complex diffs to a string, but Cloud Control doesn't seem to be happy about that. I added an update test to make sure the target scenario works end-to-end. If we find a case when the approach doesn't work, let's extend that test.

Fix patch calculation of object diffs

---

CHANGELOG.md
provider/pkg/provider/provider.go

Closes #43 
Summary: 
1. Pass the cancellable context down into any cloud control operations so they will also be cancelled.
2. Manually check for cancellation in the wait loop.
Rules for cancellation:
- Do allow cancellation during any wait operation
- Don't cancel during initial create
- Allow cancellation during most read operations*
- *Don't cancel when reading after create
Note: If the wait during create fails for any reason it returns a partial error.

Use cancelation context to handle operation cancellation

---

.github/workflows/weekly-pulumi-update.yml
provider/cmd/pulumi-gen-aws-native/examples.go

Errors are passed to the callback to allow ignoring of individual errors. In the case of an error the path and info might be nil so we need to check for the error first. This should give us more information on the failure rather than panicking.
Init submodules during weekly updates before attempting to generate the docs.

Raise errors during example files walk

---

Makefile

See #316.
The `tsc` command on line 71 will always use a globally installed TypeScript, regardless of the one installed by yarn on the previous line.

Use TypeScript package from Yarn, not global

---

CHANGELOG.md
provider/pkg/provider/ids.go
provider/pkg/provider/ids_test.go
provider/pkg/provider/provider.go

Nicely you can see that this is deterministic from the test output:
```
=== RUN   Test_getDefaultName/Name_specified_explicitly_with_no_sequence_number
ids_test.go:85: getDefaultName() = {newName} for spec: &{SdkName:autoName MinLength:0 MaxLength:0}
=== RUN   Test_getDefaultName/Name_specified_explicitly_with_sequence_number
ids_test.go:85: getDefaultName() = {newName} for spec: &{SdkName:autoName MinLength:0 MaxLength:0}
=== RUN   Test_getDefaultName/Use_old_name_with_no_sequence_number
ids_test.go:85: getDefaultName() = {oldName} for spec: &{SdkName:autoName MinLength:0 MaxLength:0}
=== RUN   Test_getDefaultName/Use_old_name_with_sequence_number
ids_test.go:85: getDefaultName() = {oldName} for spec: &{SdkName:autoName MinLength:0 MaxLength:0}
=== RUN …
```

Use sequence numbers for autonames

---

CHANGELOG.md
provider/pkg/provider/partitions.go
provider/pkg/provider/partitions_test.go
provider/pkg/provider/provider.go
provider/pkg/provider/provider_pseudo_parameters.go

Keep a mapping from regions to partitions and partitions to URL
suffixes and discover the partition for the configured region during
startup time. getUrlSuffix then returns the URL suffix for the
configured partition.

[provider] Implement getUrlSuffix.

---

CHANGELOG.md
provider/pkg/provider/provider.go
provider/pkg/schema/gen.go
sdk/dotnet/Config/Config.cs
sdk/dotnet/Provider.cs
sdk/go/aws/config/config.go
sdk/go/aws/provider.go
sdk/nodejs/config/vars.ts
sdk/nodejs/provider.ts
sdk/python/pulumi_aws_native/config/__init__.pyi
sdk/python/pulumi_aws_native/config/vars.py
sdk/python/pulumi_aws_native/provider.py

AWS Cloud Control API (and thus AWS CloudFormation) allows passing an AWS IAM Role to all resource modification actions (`CreateResource`, `UpdateResource`, `DeleteResource`, `GetResource`). The passed IAM Role is then used by the Cloud Control API to access, create, update or delete the AWS resources. With this PR an (optional) AWS IAM Role can be defined in the Provider configuration, which will then be passed to Cloud Control API.
Note, this is a unique feature for server side security enforcement, not to be confused with the already existing support for [`assumeRole`](https://github.com/pulumi/pulumi-aws-native/blob/master/provider/pkg/provider/provider.go#L348), which is used to obtain temporary client credentials.

Add support for passing AWS IAM Role to Cloud Control API

---

CHANGELOG.md
provider/pkg/provider/ids.go
provider/pkg/provider/ids_test.go
provider/pkg/provider/provider.go

Extending changes from https://github.com/pulumi/pulumi-azure-native/issues/1718 and https://github.com/pulumi/pulumi-google-native/pull/488

Revert deterministic autonaming

---

CHANGELOG.md
provider/pkg/provider/provider.go

This PR adds support for `allowedAccountIds` and `forbiddenAccountIds` to the aws-native provider.
- https://github.com/pulumi/pulumi-aws-native/issues/105
- https://github.com/pulumi/pulumi-aws-native/issues/109

Add support for allowedAccountIds and forbiddenAccountIds

---

provider/pkg/provider/ids.go
provider/pkg/provider/ids_test.go
provider/pkg/provider/provider.go

This is the new system for deterministic names with update plans. The engine will fill in the random seed with a non-deterministic slice of bytes for normal updates, but when using plans it will save and restore the bytes used thus allowing names to be deterministic between preview and update. NewUniqueName handles the case of old engines that didn't send anything for seed by just falling back to non-deterministic randomness.

Use NewUniqueName

---

CHANGELOG.md
examples/update/step1/index.ts
examples/update/step1/package.json
examples/update/step2/index.ts
examples/update/step2/package.json
provider/cmd/pulumi-resource-aws-native/metadata.json
provider/pkg/schema/convert.go
provider/pkg/schema/gen.go
provider/pkg/schema/metadata.go

Check if properties are write-only, and use an "add" if so. This is because the old values of write only properties don't show up when applying the diff within CC, so we need to do an "add".
Fixes #277 
This affects ~370 properties across 123 resources

Fix updates to write-only properties

---

examples/update/step1/index.ts
examples/update/step1/package.json
examples/update/step2/index.ts
examples/update/step2/package.json

Wait issue doesn't happen via CloudControl so can remove artificial delay. We do, however, have to remove the inline policies in step 2 to avoid deletion error: https://github.com/pulumi/pulumi-aws-native/issues/416

Use native IAM role to improve reliability

---

provider/pkg/provider/provider.go
provider/pkg/provider/provider_pseudo_parameters.go
provider/pkg/schema/gen.go
sdk/dotnet/GetPartition.cs
sdk/go/aws/getPartition.go
sdk/nodejs/getPartition.ts
sdk/python/pulumi_aws_native/get_partition.py

This was previously generated in the schema but the "pseudo parameters" have to be implemented manually, which partition was not.
- Add the partition DNS Suffix to the output as it's a crucial piece of information for users.
- Implement the partition string property as the identifier.
- Include basic documentation on what the properties will look like.
Matching the design of the classic provider - using DNS instead of URL. The source provider object, and therefore URL, is only an internal construct and not a model derived from AWS directly, so DNS seems to be a better choice for the external interface.
Fixes #742

Implement missing getPartition function

---

.github/workflows/build.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml
provider/pkg/schema/convert.go
provider/pkg/schema/convert_examples_test.go

Fixes #728
- Add testing of conversion for real resources from the real metadata.
- Add conversion of OneOf specs.
- Ignore conversions of OneOf specs which result in no change. E.g. Any

Fix conversion of dynamo table resource payloads

---

CHANGELOG.md
examples/examples_nodejs_test.go
examples/parallel-ts/Pulumi.yaml
examples/parallel-ts/index.ts
examples/parallel-ts/package.json
examples/parallel-ts/tsconfig.json
provider/pkg/provider/provider.go

Resolve #690
Resolve #854
If we try creating a significant number of cheap resources in parallel, we easily hit the max retry limit that AWS SDKs set by default (3 retry attempts). We want this to succeed by default for our users.
This PR bumps the default retry settings to more aggressive levels:
- Max attempts are set to 25, and can be overridden by the `maxRetries` config. This is the number of attempts to retry a single SDK call.
- Rate Limiter is disabled by default, can be re-enabled by the `maxRetryRateTokens` config. This is a global limit for all requests running in parallel for a single client.
- We don't touch Max Backoff - it's left on the default value of 20 seconds.
The test confirms that we can successfully create 100 IAM roles without any explicit configuration nobs.

Make retries much more aggressive by default to enable highly parallel operations

---

provider/cmd/pulumi-gen-aws-native/main.go
provider/cmd/pulumi-gen-aws-native/main_test.go

Addresses issue #901 by deleting and recreating the aws-cloudformation-schema/ dir before downloading the new schemas.
Added a new unit test to cover the directory cleaning behavior; ran `make discovery` manually to observe the impact.
I did not include the files changed as a result of running `make discovery` in this commit, but locally my diff shows two files deleted as a result of running with this change:
```
deleted:    aws-cloudformation-schema/aws-gamecast-application.json
deleted:    aws-cloudformation-schema/aws-gamecast-streamgroup.json
```
N/A
safe to revert

Clean the aws-cloudformation-schema dir before downloading new schemas

---

.gitattributes

looks like we'd intended to mark the sdk directory as generated, but the syntax was incorrect. Figured I'd also mark the cloudformation schemas as vendored as while while I'm here

fix annotation of vendored and generated code

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md
devbox.json
devbox.lock

Adds `devbox.json` and `.devcontainer` files to define a reproducible build environment. Updated the README with instructions for use.
Devbox orchestrates a nix shell with a specified dependency list, which you can use directly, or inside a container. devcontainer provides a standard for editors and other tools to work inside in a container.
I personally like this approach as a relatively lightweight way to maintain a known good build environment; I'm curious to get the team's feedback. 
Ideally, we'd drive our CI off the same docker image for consistency between local builds and CI (github has some tooling to support this already: https://github.com/devcontainers/ci); I can add this if we decide to go down this path.

RFC: Use devbox to define a consistent dev environment for contributors

---

.goreleaser.cf2pulumi.yml

'replacements' was deprecated a few months ago and was removed in a recent version 
of goreleaser (https://goreleaser.com/deprecations/#nfpmsreplacements)
Also replaced "brews/tap" with "brews/repository" as per https://goreleaser.com/deprecations/#brewstap
`goreleaser -f .goreleaser.cf2pulumi.yml check`

stop using 'replacements' options in .goreleaser.cf2pulumi.yml

---

.github/workflows/build.yml
.github/workflows/cf2pulumi-release.yml
.github/workflows/command-dispatch.yml
.github/workflows/nightly-sdk-generation.yml
.github/workflows/prerelease.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml
.github/workflows/weekly-pulumi-update.yml

@aq17 Tried to update this repo using ci-mgmt in #1001, but since this repo hasn't been using ci-mgmt there were a lot of unrelated changes, mostly to whitespace. This PR contains just the whitespace changes from #1001 to hopefully make it a little easier to evaluate a move to using ci-mgmt to manage the build tooling for this repo

Whitespace only changes to bring us closer to ci-mgmt

---

provider/pkg/provider/provider.go
provider/pkg/schema/convert.go
provider/pkg/schema/convert_examples_test.go
provider/pkg/schema/convert_test.go

Adds basic type checking errors to the internals of CfnToSdk to enable safe conversion of values
of OneOf types.
Fixes: #1009 
The CfnToSdk conversion code for values lacked any error handling and simply assumed that the value
it was handed matched the expected type. This was a problem for the conversion of values with a 
"OneOf" type as the code blindly tried to convert the value with each type in order, and
which would panic when handed a value for a later arm.
This code introduces some sanity checking around the values and uses the errors to safely find an 
arm that matches the value given.
This code should probably get a larger suite of round trip tests but for now I just added a few cases
for basic error handling and the specific situation with oneOf types that was causing the panics

Add error handling to CfnToSdk

---

.github/workflows/build.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml

Making this change to only CI verification workflow has broken the integration branch.

Apply larger runners to all workflows

---

CHANGELOG.md
examples/get-ts/index.ts
examples/parallel-ts/index.ts
provider/pkg/provider/provider.go
provider/pkg/provider/provider_test.go

Fixes: https://github.com/pulumi/pulumi-aws-native/issues/1219
This could have been a one liner, but I decided to pull out a helper method to add a test. There are a couple other values of `OperationStatus` that we may need to handle in the future, but I'm punting on those, b/c I haven't seen them in the wild and I'm not 100% sure how they ought to be handled.

Handle PENDING Operation Status  

---

CHANGELOG.md
README.md

This release contains only Cloud Formation updates until February 15. After that, we're holding off for the time being due to [this issue](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1930).

Prepare v0.97.0

---

Makefile

Fixes #1353
Avoid calling `go list ./...` from the variable which fails when embed files are missing (before we've run schema generation).

Fix warning from makefile before we're run codegen

---

provider/pkg/schema/gen.go
provider/pkg/schema/gen_tags.go
provider/pkg/schema/gen_tags_test.go
reports/unexpectedTagsShapes.json

1. Add detection of last two observed variations.
2. Add test to fail unit test if new unexpected tag styles are found.
The purpose of complete coverage of all tags styles is to maintain quality of tag accessibility. Additionally, this will allow us to reliably apply DefaultTags in a future PR (see https://github.com/pulumi/pulumi-aws-native/issues/107).

Identify all tag styles

---

provider/pkg/schema/gen.go
sdk/nodejs/package.json

Cleaning up some likely copy-pasta:
While resolving a bug caused by explicit dependencies on old nodejs packages in pulumi-kubernetes (https://github.com/pulumi/pulumi-kubernetes/issues/2857), we noticed that aws-native also has these dependencies, even though it does not need them because it does not implement any overlay resources.

Remove explicit nodejs dependencies list

---

provider/pkg/provider/provider.go

I got an error message from Pulumi saying I must set the AWS-native region value. I tried setting it with `pulumi config set aws-native:region us-east-2` multiple times, and it updated in my Pulumi.<stack>.yaml. Yet, the error persisted during `pulumi refresh`.
Setting the `AWS_REGION` environment variable resolved the problem. While this doesn't address the root cause, it offers a working alternative solution.
https://github.com/pulumi/pulumi-aws-native/issues/1356

ADD more descriptive explanation for missing aws native region config

---

examples/examples_nodejs_test.go
examples/lambda-update/step1/Pulumi.yaml
examples/lambda-update/step1/index.ts
examples/lambda-update/step1/package.json
examples/lambda-update/step1/tsconfig.json
examples/lambda-update/step2/index.ts
provider/pkg/provider/provider.go

Write-only properties can't even be read internally within the CloudControl service so they must be included in PATCH requests to ensure the updated model validates.
- Refactor where we unmarshal inputs to avoid duplicate work.
Fixes https://github.com/pulumi/pulumi-aws-native/issues/906
Might also fix https://github.com/pulumi/pulumi-aws-native/issues/1243 but there's no code to reproduce the issue.

Send unchanged write-only properties as adds on update

---

provider/cmd/pulumi-gen-aws-native/examples.go
provider/pkg/schema/convert.go
provider/pkg/schema/convert_test.go
provider/pkg/schema/gen.go
sdk/dotnet/Acmpca/Certificate.cs
sdk/dotnet/SsmContacts/Contact.cs
sdk/dotnet/SsmContacts/ContactChannel.cs
sdk/dotnet/SsmContacts/Enums.cs
sdk/go/aws/acmpca/certificate.go
sdk/go/aws/ssmcontacts/contact.go
sdk/go/aws/ssmcontacts/contactChannel.go
sdk/go/aws/ssmcontacts/pulumiEnums.go
sdk/nodejs/acmpca/certificate.ts
sdk/nodejs/ssmcontacts/contact.ts
sdk/nodejs/ssmcontacts/contactChannel.ts
sdk/nodejs/types/enums/ssmcontacts/index.ts
sdk/python/pulumi_aws_native/acmpca/certificate.py
sdk/python/pulumi_aws_native/ssmcontacts/_enums.py
sdk/python/pulumi_aws_native/ssmcontacts/contact.py
sdk/python/pulumi_aws_native/ssmcontacts/contact_channel.py

Replace unicode quotation marks U+201C and U+201D “” that we read from cloudformation files with canonical ones to avoid rendering issues in the docs.
Fix #1343

Sanitize quotation marks read from CFN files

---

Makefile

Fix regression in makefile where we expect local_generate to include the schema generation step but had lost it during refactoring in https://github.com/pulumi/pulumi-aws-native/pull/1402

Fix nightly generation

---

.github/workflows/build.yml
.github/workflows/cf2pulumi-release.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml

Reverts pulumi/pulumi-aws-native#1413
[Breaks the publishing step](https://github.com/pulumi/pulumi-aws-native/actions/runs/8280097860/job/22656434168)
```
/Users/runner/work/_temp/329c61db-f30e-4ac8-b540-d1ce697025dd.sh: line 28: numfmt: command not found
/Users/runner/work/_temp/329c61db-f30e-4ac8-b540-d1ce697025dd.sh: line 28: numfmt: command not found
sudo: docker: command not found
/Users/runner/work/_temp/329c61db-f30e-4ac8-b540-d1ce697025dd.sh: line 28: numfmt: command not found
sudo: swapoff: command not found
/Users/runner/work/_temp/329c61db-f30e-4ac8-b540-d1ce697025dd.sh: line 173: free: command not found
```

Revert "Update GitHub Actions workflows."

---

examples/lambda-update/step1/index.ts
examples/lambda-update/step2/index.ts

Avoids test failures like https://github.com/pulumi/pulumi-aws-native/actions/runs/8280190671/job/22656454104#step:25:303

Remove hard-coded name from the test to avoid concurrency failures

---

provider/pkg/provider/client/api.go
provider/pkg/provider/client/client.go
provider/pkg/provider/provider.go

Adds another client layer around Cloud Control operations to encapsulate serialization, error handling, and awaiting long-running operations.
No functional changes.

Add a Client abstraction

---

provider/pkg/provider/client/client.go
provider/pkg/provider/client/client_test.go
provider/pkg/provider/provider.go

I think I missed one low-level protocol piece that stayed in the provider but should go to the client: Resource Not Found handling. Moved it to the client now. Have thrown a few tests around it as an added benefit.
No functional changes.

Move ResourceNotFound error handling to the client level

---

provider/pkg/cf2pulumi/renderer.go

Remove all uses of contract.Assert - return errors where possible or otherwise use Assertf with additional contextual information.
Related to https://github.com/pulumi/pulumi-aws-native/issues/1304

Improve cf2pulumi error messages

---

examples/lambda-update/step1/index.ts
provider/cmd/pulumi-gen-aws-native/examples.go
provider/cmd/pulumi-gen-aws-native/main.go
provider/pkg/autonaming/semantics.go
provider/pkg/cf2pulumi/renderer.go
provider/pkg/default_tags/default_tags.go
provider/pkg/default_tags/merging.go
provider/pkg/default_tags/merging_test.go
provider/pkg/metadata/metadata.go
provider/pkg/naming/convert.go
provider/pkg/naming/convert_test.go
provider/pkg/naming/naming.go
provider/pkg/naming/naming_test.go
provider/pkg/provider/ids.go
provider/pkg/provider/ids_test.go
provider/pkg/provider/provider.go
provider/pkg/resources/validate.go
provider/pkg/schema/convert_examples_test.go
provider/pkg/schema/gen.go
provider/pkg/schema/gen_examples_test.go
provider/pkg/schema/gen_tags.go
provider/pkg/schema/gen_tags_test.go
provider/pkg/schema/inputs.go

- Move lots out from schema into smaller modules with less dependencies.
- Fix a few compiler warnings along the way.
- Rename the gen `context` struct so it doesn't block us using the `context` std lib.
- Fix flakey lambda update integration test.
This was extracted from https://github.com/pulumi/pulumi-aws-native/pull/1406

Refactor modules

---

CHANGELOG.md
provider/pkg/client/client.go
provider/pkg/client/client_test.go

The PR does three things:
1. Cover client.Create with unit tests for all branches.
2. Refactor its code to be more concise and to return as quickly as possible. Return consistent error messages.
3. Add another special case to create logic to process AlreadyExists error.
Currently, if we receive an AlreadyExists error, we follow our default flow for all await errors: we proceed to reading the resource state, we see that it exists, and we return a partial error, which saves this resource in Pulumi state. This is wrong, because we should not pull an existing resource into state unexpectedly for a user (without an import). After the fix, we hard-fail on AlreadyExists.
Fix #1263
Fix #1138

Handle AlreadyExists error during creation

---

CHANGELOG_OLD.md

Currently we have to manually update the changelog on almost every auto generated PR (e.g. [this one](https://github.com/pulumi/pulumi-aws-native/pull/1479)) which means we can't automate this process.
I am switching to automatic release note generation (re [ci-mgmt](https://github.com/pulumi/ci-mgmt/pull/882)) which will mean that the GitHub release will contain these release notes.

chore: rename CHANGELOG.md to CHANGELOG_OLD.md

---

Makefile

Previously you had to manually add the provider to the PATH for the tests to work. This automates that

Add provider to path for running integration tests

---

provider/pkg/schema/gen.go

Fixes https://github.com/pulumi/pulumi-aws-native/issues/1506
IndexStatus enum name was creating a generate-phase panic as this token was already taken.

Disambiguate QBusiness::Index Status enum

---

examples/default-tags-py/__main__.py
examples/examples_py_test.go
provider/pkg/default_tags/merging.go
provider/pkg/default_tags/merging_test.go

Previously the default tags where randomly appended to the tag list because of Go's random iteration order for maps. This introduces sorting for the key's of the default tags in order to produce deterministic tag lists and prevent permadiffs.
Fixes #1486

Deterministically sort default tags to prevent permadiff

---

Makefile

The awk command of the `discovery` make target was not correctly escaped and ended up discovering the wrong version.
Instead of detecting `8bed56da0b8e0f6bb7c2d255194694bba97bb28f` it detected `8bed56da0b8e0f6bb7c2d255194694bba97bb28f	refs/heads/main` which ended up breaking the docs generation.
fixes #1609

Fix make target "discovery" by correctly escaping commands

---

provider/cmd/pulumi-gen-aws-native/main.go
provider/pkg/schema/gen.go

Fixes https://github.com/pulumi/pulumi-aws-native/issues/1704
Review commit by commit.
First add more visible log fencing - without that I first incorrectly diagnosed the blocker as https://github.com/pulumi/pulumi-aws-native/issues/1706 where it was another issue repsonsible.
Second fix the blocker issue: instead of failing on dangling references, tolerate them.

Fix nightly generation failure

---

README.md
examples/aws-native-ts-stepfunctions/Pulumi.yaml
examples/aws-native-ts-stepfunctions/README.md
examples/aws-ts-assume-role/README.md
examples/ecs/Pulumi.yaml
examples/get-ts/Pulumi.yaml
examples/lambda-update/step1/Pulumi.yaml
examples/simple-go/Pulumi.yaml
examples/simple-ts/Pulumi.yaml
examples/update/step1/Pulumi.yaml
examples/update/step2/Pulumi.yaml
examples/write-only-go/Pulumi.yaml
provider/pkg/schema/gen.go
sdk/dotnet/Provider.cs
sdk/go/aws/provider.go
sdk/nodejs/package.json
sdk/nodejs/provider.ts
sdk/python/pulumi_aws_native/provider.py
sdk/python/pyproject.toml

Updates references from `AWS Native` to `AWS Cloud Control`
re #1296

Rename project to AWS Cloud Control Provider

---

provider/pkg/resources/patching.go
provider/pkg/resources/patching_test.go

Currently, when calculating the json patch for a resource with
write only properties but no diff we panic with a nil pointer
dereference.
This change fixes that by adding special handling for that
case.
This situation can happen when:
- The resource was created
- Cloud Control reported it as failed but it actually succeeded (intermittent failure)
- On the next run, Pulumi detects an update (to complete the operation) but the properties are still the same
- We calculate the diff between A and A and get an empty diff (nil)
- Panic in patch calculation
Fixes #1755

Fix nil pointer panic when calculating patches

---

provider/pkg/provider/provider_intrinsics.go
provider/pkg/provider/provider_intrinsics_test.go

The `cidr` intrinsic function has been broken. This PR fixes the cidr function and adds some tests. Took some inspiration from [OpenTofu cidrsubnets](https://github.com/opentofu/opentofu/blob/9d842aa920e16cc3275f4fe54240634fff5146dc/internal/lang/funcs/cidr.go#L123)
fixes #1566, fixes #593

Fix cidr intrinsic

---

provider/pkg/provider/provider.go

This change does not affect the code behavior but makes it clear that AWS Native never cascade-replaces resources in DiffConfig.

chore: clarify DiffConfig code

---

provider/pkg/client/client.go
provider/pkg/client/client_test.go

Introduces a retry for NotFound errors from GetResource executed right after Create. 
Based on the logs from our CI runs we suspect eventual consistency in AWS may cause some resources to fail with NotFound in Get even after WaitForResourceOpCompletion succeeded.
Relates: pulumi/pulumi-aws-native#1186

Retry GetResource NotFound when creating

---

provider/pkg/naming/convert.go
provider/pkg/naming/convert_test.go
provider/pkg/resources/checkpoint.go
provider/pkg/resources/checkpoint_test.go

This change adds utility methods needed for supporting CloudFormation custom resources.
The main part of this change is a method for deeply converting all primitive values in a `map[string]interface{}` to strings. This is needed because CloudFormation has this behavior: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1037

Add utility functions for supporting CloudFormation CustomResources

---

provider/go.mod
provider/go.sum
provider/pkg/metadata/metadata.go
provider/pkg/resources/cfn_custom_resource.go
provider/pkg/resources/cfn_custom_resource_test.go

This PR adds support for [CloudFormation Custom Resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html) to the aws-native provider. It implements an emulator that enables Pulumi programs to interact with Lambda-backed CloudFormation Custom Resources.
A CloudFormation custom resource is essentially an extension point to run arbitrary code as part of the CloudFormation lifecycle. It is similar in concept to the [Pulumi Command Provider](https://www.pulumi.com/registry/packages/command/), the difference being that CloudFormation CustomResources are executed in the Cloud; either through Lambda or SNS.
For the first implementation we decided to limit the scope to Lambda backed Custom Resources, because the SNS variants are not widely used.
The …

Add implementation for CloudFormation Custom Resource Emulator

---

examples/cfn-custom-resource/README.md
provider/pkg/schema/docs/content/cfn-custom-resource.md
sdk/dotnet/CloudFormation/CustomResourceEmulator.cs
sdk/go/aws/cloudformation/customResourceEmulator.go
sdk/nodejs/cloudformation/customResourceEmulator.ts

This change adds a Readme for the CFN Custom Resource example and links it in the registry docs.

Link registry docs to example for CFN Custom Resource

---

provider/pkg/client/client.go
provider/pkg/client/client_test.go

It appears that the CDK test suite is still failing, so this change adjusts the backoff/retry on Resource.Get to be more generous and allow more time. 
https://github.com/pulumi/pulumi-cdk/actions/runs/11818972903/job/32927805461?pr=212

Additional backof delay for retrying Resource.Get Not Found

---

provider/pkg/naming/convert.go
provider/pkg/naming/convert_test.go

This change fixes the conversion of Pulumi input properties to the format expected by the CloudControl API in the case when Pulumi schema specifies a union type (OneOf) without a discriminator. Previously the first matching case would be picked which could erroneously send empty data to CloudControl. With this change a heuristic is run instead to pick the non-error case with the largest map or array.
In the long term it would be better to support discriminators and manage their metadata (#1849).
Fixes #1846

Fixes union type conversions to CloudControl

---

codecov.yml

I'm assuming since this is just tooling to generate the ref metadata, we don't feel like it needs to be covered with extensive testing.

Exclude tools dir fom codecov

---

provider/pkg/metadata/metadata.go
provider/pkg/schema/gen.go

primaryIdentifier is a CloudControl concept that with this change will be exposed in the provider metadata. One of the use cases is correlating identifiers when importing state provisioned by `cdk` into `pulumi-cdk` managed stacks.

Expose primary identifier information in the metadata

---

sdk/nodejs/invoicing/getInvoiceUnit.ts
sdk/nodejs/logs/getIntegration.ts
sdk/nodejs/memorydb/getMultiRegionCluster.ts
sdk/python/pulumi_aws_native/invoicing/get_invoice_unit.py
sdk/python/pulumi_aws_native/logs/get_integration.py
sdk/python/pulumi_aws_native/memorydb/get_multi_region_cluster.py

Merging both #1870 and #1875 on top of each other caused the SDK to go out of sync. This PR just regenerates the SDK to get a passing build again.
Fixes https://github.com/pulumi/pulumi-aws-native/issues/1877

Regenerate SDK

---

provider/pkg/resources/patching_test.go

This commit removes a dependency on `pulumi/pulumi/sdk/go/common/slice` for a single small function, `Map`, which is cheaply vendored. Doing so allows us to clean up the public API of `pulumi/pulumi/sdk/go/common` and also chip away at dependencies for `pulumi-aws-native`.

Remove dependency on `pu/pu/sdk/go/common/slice`

---

Makefile

I don't know why we were running `git clean` here, but we don't do that
in any other providers. This is preventing our check worktree clean job
to correctly catch when new sdk files are not checked in.
fixes #1827

chore: do not clean untracked files

---

examples/examples_nodejs_test.go
examples/go.mod
examples/go.sum
examples/refresh-changes/.gitignore
examples/refresh-changes/Pulumi.yaml
examples/refresh-changes/index.ts
examples/refresh-changes/package.json
examples/refresh-changes/tsconfig.json
provider/pkg/provider/provider.go

This PR fixes an issue where the `Read` method was returning the
previous (oldState) inputs which meant that refresh operations never
showed any changes.
fixes #1796

Fix refresh does not show changes

---

provider/pkg/metadata/metadata.go
provider/pkg/schema/gen.go
provider/pkg/schema/resource_props.go
provider/pkg/schema/resource_props_test.go

This PR adds `readOnlyProperties` to the pulumi metadata. It also fixes
an issue with all properties (`readOnly/createOnly/writeOnly`) where
nested properties where not converted to the correct sdk name value.

chore: add readOnlyProperties to metadata

---

provider/pkg/autonaming/application.go
provider/pkg/autonaming/application_test.go
provider/pkg/autonaming/semantics.go
provider/pkg/provider/provider.go
provider/pkg/provider/provider_2e2_test.go
provider/pkg/provider/provider_test.go
provider/pkg/provider/testdata/autonaming/Pulumi.yaml
provider/pkg/resources/cfn_custom_resource.go
provider/pkg/resources/cfn_custom_resource_test.go
provider/pkg/resources/custom.go
provider/pkg/resources/extension_resource.go
provider/pkg/resources/mock_custom_resource.go

This PR implement the AWS Native part of https://github.com/pulumi/pulumi/issues/1518. See https://github.com/pulumi/pulumi/discussions/17592 for the full design.
In short, https://github.com/pulumi/pulumi/pull/17810 introduced the protobuf changes required for the provider-side implementation. With those, a provider can:
- Declare that it supports autonaming configurations with a response flag in Configure
- Accept two extra properties in CheckRequest: a proposed name and a mode to apply it
This PR applies those parameters to auto-name calculation if they are specified:
- In Disabled mode, we don't calculate auto-names and let the resource validation fail if an explicit name is not specified. For that, I had to thread an extra `bool` flag through autonaming machinery.
- In Enforce mode, …

Implement autonaming configuration protocol

---

provider/pkg/provider/provider_2e2_test.go
provider/pkg/provider/testdata/autonaming/Pulumi.yaml

`TestAutonaming` occasionally fails if test runs are running within 1 minute of each other because SQS does not allow recreating a deleted queue within 60s:
```
aws-native:sqs:Queue (queue):
error: creating resource: creating resource (await): operation CREATE failed with "Throttling": You must wait 60 seconds after deleting a queue before you can create another with the same name. (Service: Sqs, Status Code: 400, Request ID: 7503e9ea-2fa2-5fba-b1cc-b6117f9af4d4)
```
To fix this I added some random parts to the resource name
Fixes https://github.com/pulumi/pulumi-aws-native/issues/1983

Fix TestAutonaming flakiness

---

.github/workflows/build.yml
.github/workflows/nightly-sdk-generation.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml

This switches the AWS Access from hardcoded access keys that are pulled
from GitHub secrets to use Pulumi ESC environments.
re https://github.com/pulumi/home/issues/3731, re https://github.com/pulumi/ci-mgmt/pull/1453

Switch AWS access to use ESC

---

Makefile
sdk/java/build.gradle

Updates Java generation and SDK to 1.16.0
This should re-enable the ability to publish to Maven Central after OSSRH is sunset.
Part of the larger roll-out https://github.com/pulumi/ci-mgmt/issues/1611

Java 1.16.0
